version: "3.8"

services:
  nats-server:
    image: nats:latest
    ports:
      - ${NATS_SERVER_PORT}:${NATS_SERVER_PORT}

  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS_HOST}

  auth-ms:
    build: ./auth-ms
    ports:
      - ${AUTH_PORT}:${AUTH_PORT}
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=${AUTH_PORT}
      - NATS_SERVERS=${NATS_SERVERS_HOST}
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${AUTH_JWT_SECRET}

  products-ms:
     build: ./products-ms
     ports:
       - ${PRODUCTS_MS_PORT}:${PRODUCTS_MS_PORT}
     volumes:
       - ./products-ms/src:/usr/src/app/src
     command: yarn start:dev
     environment:
       - PORT=${PRODUCTS_MS_PORT}
       - DATABASE_URL=${PRODUCTS_DATABASE_URL}
       - NATS_SERVERS=${NATS_SERVERS_HOST}

  orders-ms:
     depends_on:
       - orders-db
     build: ./orders-ms
     ports:
       - ${ORDERS_MS_PORT}:${ORDERS_MS_PORT}
     volumes:
       - ./orders-ms/src:/usr/src/app/src
     command: yarn start:dev
     environment:
       - PORT=${ORDERS_MS_PORT}
       - DATABASE_URL=${ORDERS_DATABASE_URL}
       - NATS_SERVERS=${NATS_SERVERS_HOST}

  orders-db:
     container_name: orders_database
     image: postgres:16.2
     restart: always  #reiniciar el contenedor si se detiene
     ports:
       - ${ORDERS_DB_PORT}:${ORDERS_DB_PORT}
     volumes:
       - ./orders-ms/postgres:/var/lib/postgresql/data
     environment:
       - POSTGRES_USER=${ORDERS_POSTGRES_USER}
       - POSTGRES_PASSWORD=${ORDERS_POSTGRES_PASSWORD}
       - POSTGRES_DB=${ORDERS_POSTGRES_DB}

  payments-ms:
     build: ./payments-ms
     ports:
       - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
     volumes:
       - ./payments-ms/src:/usr/src/app/src
     command: yarn start:dev
     environment:
       - PORT=${PAYMENTS_MS_PORT}
       - NATS_SERVERS=${NATS_SERVERS_HOST}
       - STRIPE_SUCCESS_URL=${PAYMENTS_MS_STRIPE_SUCCESS_URL}
       - STRIPE_CANCEL_URL=${PAYMENTS_MS_STRIPE_CANCEL_URL}
       - STRIPE_SECRET=${PAYMENTS_MS_STRIPE_SECRET}
       - STRIPE_ENDPOINT_SECRET=${PAYMENTS_MS_STRIPE_ENDPOINT_SECRET}
       - STRIPE_ENDPOINT_SECRET_TESTING=${PAYMENTS_MS_STRIPE_ENDPOINT_SECRET_TESTING}
